language: c

os:
  - linux
  - osx

env:
  - LLVM=no
  - LLVM=llvm

sudo: required
dist: trusty

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq update; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get -qq install gcc-5 g++-5; fi

script: make test
